export {ReactComponent as UserSvg} from '../assets/icons/user.svg';
export {ReactComponent as EmailSvg} from '../assets/icons/mail.svg';
export {ReactComponent as PhoneSvg} from '../assets/icons/phone.svg';
export {ReactComponent as ShowSvg} from '../assets/icons/show.svg';
export {ReactComponent as HideSvg} from '../assets/icons/hide.svg';
export {ReactComponent as GlobeSvg} from '../assets/icons/globe.svg';
export {ReactComponent as EditSvg} from '../assets/icons/edit.svg';
export {ReactComponent as CloseSvg} from '../assets/icons/close.svg';
export {ReactComponent as FileCheckSvg} from '../assets/icons/file_check.svg';